Sgs.Attendance.Mvc/Controllers/DevicesInfoController.cs
using AutoMapper;
using Microsoft.Extensions.Logging;
using Sameer.Shared;
using Sgs.Attendance.Mvc.Models;
using Sgs.Attendance.Mvc.ViewModels;

namespace Sgs.Attendance.Mvc.Controllers
{
    public class DevicesInfoController : GeneralMvcController<DeviceInfoModel, DeviceInfoViewModel>
    {
        public DevicesInfoController(IDataManager<DeviceInfoModel> dataManager, IMapper mapper
            , ILogger<GeneralMvcController<DeviceInfoModel, DeviceInfoViewModel>> logger) : base(dataManager, mapper, logger)
        {
        }
    }
}

Sgs.Attendance.Mvc/Controllers/WorkShiftsSystemsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sameer.Shared;
using Sgs.Attendance.Mvc.Models;
using Sgs.Attendance.Mvc.Services;
using Sgs.Attendance.Mvc.ViewModels;

namespace Sgs.Attendance.Mvc.Controllers
{
    public class WorkShiftsSystemsController : GeneralMvcController<WorkShiftsSystemModel, WorkShiftsSystemViewModel>
    {
        public WorkShiftsSystemsController(IDataManager<WorkShiftsSystemModel> dataManager, IMapper mapper, ILogger<WorkShiftsSystemsController> logger) 
            : base(dataManager, mapper, logger)
        {
        }

        protected override Task<WorkShiftsSystemViewModel> createObject()
        {
            return  Task.FromResult(new WorkShiftsSystemViewModel { StartDate=DateTime.Today.AddDays(-1) });
        }

        protected override string createNewTitleMessage => "إضافة نظام ورديات جديد";

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> VerifyCode(string code, int? id = null)
        {
            try
            {
                var dataByCode = await ((GeneralApiDataManager<WorkShiftsSystemModel>)_dataManager).GetAllDataList("code",code);
                if (dataByCode != null && dataByCode.Any() && dataByCode.FirstOrDefault().Id != id)
                {
                    return Json($"عفواً رمز نظام الورديات مسجل مسبقاً !");
                }
                return Json(true);
            }
            catch (Exception)
            {
                return Json("خطأ أثناء التحقق ...!!");
            }
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> VerifyName(string name, int? id = null)
        {
            try
            {
                var dataByCode = await ((GeneralApiDataManager<WorkShiftsSystemModel>)_dataManager).GetAllDataList("name", name);
                if (dataByCode != null && dataByCode.Any() && dataByCode.FirstOrDefault().Id != id)
                {
                    return Json($"عفواً اسم نظام الورديات مسجل مسبقاً !");
                }
                return Json(true);
            }
            catch (Exception)
            {
                return Json("خطأ أثناء التحقق ...!!");
            }
        }

        protected override IActionResult editView(WorkShiftsSystemViewModel currentData)
        {
            return View("create", currentData);
        }
    }
}

Sgs.Attendance.Mvc/Views/Shared/_Clock.cshtml
<div class="header-clock">
    <div class="clock">
        <div class="inner">
            <div class="hour hand"></div>
            <div class="minute hand"></div>
            <div class="second hand"></div>
            <div class="graduations">
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
                <div class="graduation"></div>
            </div>
        </div>
    </div>
</div>

Sgs.Attendance.Mvc/Views/Shared/_Footer.cshtml
<div class="container">
    <span class="text-muted"><i class="far fa-copyright fa-fw fa-lg"></i> @DateTime.Today.Year - Saudi Geological Survey </span>
    <span class="text-muted float-right" dir="rtl"><i class="far fa-copyright fa-fw fa-lg"></i> @DateTime.Today.GetInfo(true).year - هيئة المساحة الجيولوجية السعودية</span>
</div>

Sgs.Attendance.Mvc/Views/Shared/_Header.cshtml
<div class="header-top">
    <div class="header-title"></div>
    <partial name="_clock" />
    <div class="header-logo">
        @*<img src="~/Images/logo.png" height="120px;" width="160px"/>*@
    </div>
</div>

Sgs.Attendance.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- for FF, Chrome, Opera -->
    <link rel="icon" type="image/png" href="~/Images/SGS-ICON.ico" sizes="16x16">
    <link rel="icon" type="image/png" href="~/Images/SGS-ICON.ico" sizes="32x32">

    <!-- CSS -->
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/node_modules/@@fortawesome/fontawesome-free-webfonts/css/fontawesome.css" rel="stylesheet" />
    <link href="~/node_modules/@@fortawesome/fontawesome-free-webfonts/css/fa-solid.css" rel="stylesheet" />
    <link href="~/node_modules/@@fortawesome/fontawesome-free-webfonts/css/fa-regular.css" rel="stylesheet" />
    <link href="~/node_modules/@@fortawesome/fontawesome-free-webfonts/css/fa-brands.css" rel="stylesheet" />
    <link href="~/node_modules/toastr/build/toastr.css" rel="stylesheet" />


    <environment include="Development">

        @*<link rel="stylesheet" href="~/Styles/Kendo/kendo.common-material.min.css" />*@
        @*<link rel="stylesheet" href="~/Styles/Kendo/kendo.material-v2.min.css" />*@
        @*<link rel="stylesheet" href="~/Styles/kendo.custom.css" />*@
        <link rel="stylesheet" href="~/Styles/all.css" />
        <link rel="stylesheet" href="~/Styles/Kendo/kendo.rtl.min.css" />
    </environment>

    <environment exclude="Development">

        <link rel="stylesheet"
              href="https://kendo.cdn.telerik.com/2018.3.1017/styles/kendo.common-nova.min.css"
              asp-fallback-href="~/Styles/Kendo/kendo.common-nova.min.css"
              asp-fallback-test-class="k-common-test-class"
              asp-fallback-test-property="opacity" asp-fallback-test-value="0" />

        <link rel="stylesheet"
              href="https://kendo.cdn.telerik.com/2018.3.1017/styles/kendo.nova.min.css"
              asp-fallback-href="~/Styles/Kendo/kendo.nova.min.css"
              asp-fallback-test-class="k-theme-test-class"
              asp-fallback-test-property="opacity" asp-fallback-test-value="0" />

    </environment>

    <link href="~/Styles/main.css" rel="stylesheet" />
    <link href="~/Styles/header.css" rel="stylesheet" />
    <link href="~/Styles/footer.css" rel="stylesheet" />

    <environment include="Development">

        <script src="~/node_modules/jquery/dist/jquery.js"></script>

        @* Place Kendo UI scripts after jQuery *@
        <script src="~/Scripts/Kendo/kendo.all.min.js"></script>
        <script src="~/Scripts/Kendo/kendo.aspnetmvc.min.js"></script>
        <script src="~/Scripts/Kendo/cultures/kendo.culture.es-US.min.js"></script>

    </environment>

    <environment exclude="Development">

        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
         </script>

        <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/kendo.all.min.js"
                asp-fallback-src="~/Scripts/Kendo/kendo.all.min.js"
                asp-fallback-test="window.kendo">
        </script>
        <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/kendo.aspnetmvc.min.js"
                asp-fallback-src="~/Scripts/Kendo/kendo.aspnetmvc.min.js"
                asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
        </script>

    </environment>

    <title>@ViewBag.Title</title>

    @RenderSection("header", required: false)

</head>
<body>

    <div class="main-Container">
        <header>
            <partial name="_Header" />
        </header>


        <partial name="_Navbar" />
        <main class="k-rtl">
            @RenderBody()
        </main>

        <footer>
            <partial name="_Footer" />
        </footer>
    </div>

    <!-- Script files -->
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/node_modules/toastr/build/toastr.min.js"></script>
    <script src="~/Scripts/toastr-options.js"></script>
    <script src="~/Scripts/clock.js"></script>
    <script src="~/Scripts/app.js"></script>


    <partial name="_LayoutScript"/>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Sgs.Attendance.Mvc/Views/Shared/_LayoutScript.cshtml
<script>

        (function () {

            $(function () {

                var statusMessage;

                @if(!string.IsNullOrEmpty(@ViewData["StatusMessage"]?.ToString()))
                {
                    @:statusMessage = "@ViewData["StatusMessage"]";
                }

                if (statusMessage) {
                    if (statusMessage.toUpperCase().includes("SUCC")) {
                        toastr.success(statusMessage);
                    }
                    else if (statusMessage.toUpperCase().includes("ERROR")) {
                        toastr.error(statusMessage);
                    }
                    else if (statusMessage.toUpperCase().includes("CANCEL")) {
                        toastr.warning(statusMessage);
                    }
                    else {
                        toastr.info(statusMessage);
                    }
                }
                else {
                    toastr.info("@ViewData["Title"]");
                }

            })

    })();

    kendo.culture("en-US");

</script>

Sgs.Attendance.Mvc/Views/Shared/_Navbar.cshtml
<div class="container" style="margin-top:80px;text-align:center;direction:rtl;">
    <ul class="nav nav-tabs">
        <li class="nav-item" style="width:140px">
            <a is-active-controller asp-controller="Home" asp-action="index" class="nav-link">الرئيسية</a>
        </li>
        <li class="nav-item" style="width:140px">
            <a is-active-controller asp-controller="WorkShiftsSystems" asp-action="index" class="nav-link">أنظمة الورديات</a>
        </li>
        <li class="nav-item" style="width:140px">
            <a is-active-controller asp-controller="DepartmentsInfo" asp-action="indexAsync" class="nav-link">الهيكل الإداري</a>
        </li>
        <li class="nav-item" style="width:140px">
            <a is-active-controller asp-controller="DevicesInfo" asp-action="indexAsync" class="nav-link">أجهزة البصمة</a>
        </li>
        <li class="nav-item" style="width:140px">
            <a is-active-controller asp-controller="DevicesInfo" asp-action="indexAsync" class="nav-link">الهيكل الاداري</a>
        </li>
    </ul>
</div>

Sgs.Attendance.Mvc/Views/Shared/_ValidationScripts.cshtml
<environment names="Development">
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"
            asp-fallback-src="~/node_modules/jquery-validation/dist/jquery.validate.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
    </script>
</environment>